C:\BIN\SYSTEM AUTONET
c:\bin\SYSTEM TROG
DS NE /S
PCOPY d:\video\TROG\*.ASM i:\ /U /dc /S /V /BA
PCOPY d:\video\TROG\*.CMD i:\ /U /dc /S /V /BA
PCOPY d:\video\TROG\*.OUT i:\ /U /dc /S /V /BA
PCOPY d:\video\TROG\*.BAT i:\ /U /dc /S /V /BA
c:\bin\SYSTEM IMG
DS NE /S
PCOPY e:\video\img\TROG*.IMG i:\ /U /dc /S /V /BA
PCOPY e:\video\img\TROG*.BD* i:\ /U /dc /S /V /BA
PCOPY e:\video\img\TROG*.LOD i:\ /U /dc /S /V /BA
PCOPY C:\BIN\*.* i:\ /U /dc /S /V /BA
PCOPY C:\BAT\*.* i:\ /U /dc /S /V /BA
c:\bin\SYSTEM TROG


