C:\BIN\SYSTEM AUTONET
c:\bin\SYSTEM TROG
DS NE /S
PCOPY d:\video\TROG\*.ASM i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\*.CMD i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\*.OUT i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\*.LIB i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\*.H i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\*.TVS i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\makefile i:\trog\trog /U /V /BA /SA
PCOPY d:\video\TROG\sound\*.pp i:\trog\trog\sound /U /V /BA /SA
c:\bin\SYSTEM IMG
DS NE /S
PCOPY e:\video\img\TROG*.IMG i:\trog\img /U /V /BA /SA
PCOPY e:\video\img\TROG*.BD* i:\trog\img /U /V /BA /SA
PCOPY e:\video\img\TROG*.LOD i:\trog\img /U /V /BA /SA
c:\bin\SYSTEM TROG


