C:\BIN\SYSTEM AUTONET
c:\bin\SYSTEM TROG
PCOPY i:\trog\trog\*.ASM d:\video\TROG /A /V /BA /R /SA
PCOPY i:\trog\trog\*.CMD d:\video\TROG /A /V /BA /R /SA
PCOPY i:\trog\trog\*.OUT d:\video\TROG /A /V /BA /R /SA
PCOPY i:\trog\trog\*.LIB d:\video\TROG /A /V /BA /R /SA
PCOPY i:\trog\trog\*.H d:\video\TROG /A /V /BA /R /SA
PCOPY I:\trog\trog\*.TVS d:\video\trog /A /V /BA /R /SA
PCOPY i:\trog\trog\makefile d:\video\TROG /A /V /BA /R /SA
DS NE /S
c:\bin\SYSTEM IMG
PCOPY i:\trog\img\TROG*.IMG e:\video\img /A /V /BA /R /SA
PCOPY i:\trog\img\TROG*.BD* e:\video\img /A /V /BA /R /SA
PCOPY i:\trog\img\TROG*.LOD e:\video\img /A /V /BA /R /SA
DS NE /S
c:\bin\SYSTEM TROG

